config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :user_sessions
  resources :decks do
    resources :cards, shallow: true
  end
  resources :users do
    put "pick_deck", on: :member
  end
  put "review_card", to: "static_pages#review_card"
  get "landing", to: "static_pages#landing"

  get "login" => "user_sessions#new", :as => :login
  post "logout" => "user_sessions#destroy", :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :deck
  before_create :set_default_review_date, :downcase_translated_text
  validates :original_text, uniqueness: true, presence: true
  validates :translated_text, :user_id, :deck_id, presence: true
  validate :original_text_cannot_be_equal_to_translated_text
  mount_uploader :image, ImageUploader

  scope :for_review, -> { where('review_date <= ?', Time.now).order("RANDOM()") }

  def check_answer(translation, time)
    translation = translation.mb_chars.downcase.to_s
    levenshtein_check_result = Levenshtein.distance(translated_text, translation)
    if [0, 1].include?(levenshtein_check_result)
      handle_correct_answers
    else
      handle_incorrect_answers
    end
    change_review_date(levenshtein_check_result, time)
    levenshtein_check_result
  end

  def change_review_date(typo, time)
    super_memo = SuperMemo.new(interval, correct_answers_counter, ef, time, typo)
    update_attributes(interval: super_memo.interval,
                      ef: super_memo.ef,
                      review_date: super_memo.interval.days.from_now)
  end

  def handle_correct_answers
    self.incorrect_answers_counter = 0
    increment(:correct_answers_counter)
    save
  end

  def handle_incorrect_answers
    self.correct_answers_counter = 0
    increment(:incorrect_answers_counter)
    save
  end

  def original_text_cannot_be_equal_to_translated_text
    if original_text.downcase == translated_text.downcase
      errors.add(:base, "Original text and translated must be different")
    end
  end

  def set_default_review_date
    self.review_date = Time.now
  end

  def downcase_translated_text
    self.translated_text = translated_text.mb_chars.downcase.to_s
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  validates :title, :user_id, presence: true
  has_many :cards, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :cards, dependent: :destroy
  has_many :decks, dependent: :destroy
  has_many :authentications, dependent: :destroy
  belongs_to :current_deck, class_name: "Deck", foreign_key: "current_deck_id"
  accepts_nested_attributes_for :authentications
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: [:show, :edit, :update, :destroy]
  before_action :find_deck, only: [:index, :new, :create]
  before_action :require_login

  def index
    @cards = @deck.cards
  end

  def show
  end

  def new
    @card = @deck.cards.new
  end

  def create
    @card = @deck.cards.new(cards_params.merge(user: current_user))

    if @card.save
      redirect_to deck_cards_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @card.update(cards_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
    #@deck = Deck.find(@card.deck_id)
    @deck = @card.deck
    @card.destroy
    redirect_to deck_cards_path(@deck)
  end

  private

  def find_deck
    @deck = current_user.decks.find(params[:deck_id])
  end

  def find_card
    @card = current_user.cards.find(params[:id])
  end

  def cards_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :remote_image_url)
  end

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = current_user.decks
  end

  def new
    @deck = current_user.decks.new
  end

  def create
    @deck = current_user.decks.new(decks_params)
    if @deck.save
      redirect_to decks_path, notice: "New deck was created"
    end
  end

  def destroy
    @deck = current_user.decks.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end

  private

  def decks_params
    params.require(:deck).permit(:title)
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end

  private

  def auth_params
    params.permit(:provider, :oauth_token, :oauth_verifier)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if current_user
      if current_user.decks.present?
        if current_user.current_deck
          @cards = current_user.current_deck.cards
        else
          @cards = current_user.cards
        end
        @card = @cards.for_review.first
      else
        redirect_to decks_path, notice: "Для начала тренировок создайте колоду"
      end
    else
      redirect_to landing_path
    end
  end

  def landing
  end

  def review_card
    @card = Card.find(params[:card_id])
    @translation = params[:translation]
    @check_translation = @card.check_answer(@translation, params[:time])
    if @check_translation == 0
      flash[:right] = "Правильный ответ"
    elsif @check_translation == 1
      flash[:right] = "Правильно! Вы допустили одну опечатку: #{@translation}. Правильно: #{@card.translated_text}."
    else
      flash[:wrong] = "Неправильный ответ"
    end
    redirect_to root_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_login, only: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:user_sessions][:email], params[:user_sessions][:password])
      redirect_back_or_to root_path, notice: "Login successful"
    else
      flash.now[:alert] = "Login failed"
      render "new"
    end
  end

  def destroy
    logout
    redirect_to :login, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: "User was successfully created."
    else
      render "new"
    end
  end

  def pick_deck
    current_user.update_columns(current_deck_id: params[:current_deck_id])
    redirect_to root_path, notice: "Current deck was picked"
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation, :authentications_attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for [@deck, @card], html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <%= f.file_field :image %>
  <%= f.text_field :remote_image_url, label:"or image URL" %>
  <%= f.error :base %>
  <%= f.button :submit %>
<% end %>

app/views/cards/edit.html.erb
<%= render "form" %>

app/views/cards/index.html.erb
<% @cards.each do |card| %>
  <div class= "card">
    <div class="upload-image">
      <%= image_tag card.image_url(:thumb) %>
    </div>
    <div class="original-txt">
      <p><%= card.original_text %></p>
    </div>
    <div class="translated-txt">
      <p><%= card.translated_text %></p>
    </div>
    <span><%= card.review_date.strftime("%d/%m/%Y/ %H:%M") %></span>
    <span><%= card.correct_answers_counter %></span>
    <span><%= card.incorrect_answers_counter %></span>
    <div>
      <%= link_to "Изменить", edit_card_path(card) %>
      <%= link_to "Удалить", card, method: :delete, data: { confirm: 'Are you sure?'} %>
    </div>
  </div>
<% end %>

app/views/cards/new.html.erb
<%= render "form" %>

app/views/cards/show.html.erb
<div class= "card">
  <div class="upload-image">
    <%= image_tag @card.image_url(:thumb) %>
  </div>
  <div class="original-txt">
    <p><%= @card.original_text %></p>
  </div>
  <div class="translated-txt">
    <p><%= @card.translated_text %></p>
  </div>
  <span><%= @card.review_date.strftime("%d/%m/%Y") %></span>
  <div>
    <%= link_to "Изменить", edit_card_path(@card) %>
    <%= link_to "Удалить", @card, method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>
</div>

app/views/decks/_form.html.erb
<%= simple_form_for @deck do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.error :base %>
  <%= f.button :submit%>
<% end %>

app/views/decks/index.html.erb
<p>
  <%= link_to "Add a deck", new_deck_path   %>
</p>
<% @decks.each do |deck| %>
  <div class="deck">
    <h2>
      <%= deck.title %>
    </h2>
    <ul>
    <li>
      <%= link_to "Add a card", new_deck_card_path(deck) %>
    </li>
    <li>
      <%= link_to "Show cards", deck_cards_path(deck) %>
    </li>
    <li>
      <%= link_to "Set as current", pick_deck_user_path(deck, current_deck_id: deck.id), method: :put %>
    </li>
    <li>
      <%= link_to "Delete deck", deck, method: :delete, data: { confirm: 'Are you sure?'} %>
    </li>
  </ul>
  </div>
<% end %>

app/views/decks/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcardr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="container">
    <header class="clearfix">
      <h1><%= link_to "Флэшкарточкер", root_path %></h1>
      <ul class="navigation-links">
        <% if current_user %>
          <li><%= link_to "Менеджер колод", decks_path %></li>
          <li><%= link_to "Logout", :logout, method: :post %></li>
        <% else %>
          <li><%= link_to "Login", :login %></li>
          <li><%= link_to 'Login with Twitter', auth_at_provider_path(provider: :twitter) %></li>
          <li><%= link_to 'Login with Github', auth_at_provider_path(provider: :github) %></li>
        <% end %>
      </ul>
    </header>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <section>
      <%= yield %>
    </section>
  </section>
</body>
</html>

app/views/static_pages/home.html.erb
<% if @card %>
  <div class="card">
    <div class="upload-image">
      <%= image_tag @card.image_url(:thumb) %>
    </div>

    <div class="original-txt">
      <p><%= @card.original_text %></p>
    </div>
    <%= form_tag review_card_path, method: :put do %>
      <%= text_field_tag(:translation, nil, placeholder: 'Enter translation here') %>
      <%= hidden_field_tag "card_id", @card.id %>
      <%= hidden_field_tag "time", 0 %>
      <%= submit_tag("Check", id: "answer_submit") %>
    <% end %>
  </div>
<% else %>
  <p class="end-training">Добавьте карточек или выберете другую колоду</p>
<% end %>

app/views/static_pages/landing.html.erb
<p>Первый в мире удобный менеджер флеш-карточек. Именно так.</p>
<p>Займись своим языком!</p>
<%= link_to "Зарегистрируйся сейчас", new_user_path %>

app/views/user_sessions/_form.html.erb
<%= simple_form_for :user_sessions,{ url: user_sessions_path } do |f| %>
  <%= f.input :email, label: "email"  %>
  <%= f.input :password, label: "password"  %>
  <%= f.button :submit, "Sign In" %>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<p> Best approach to learn English</p>
<%= render 'form' %>

<p>"Нет аккаунта? <%= link_to 'Зарегистрируйтесь', new_user_path %> </p>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
  <%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.error :base %>
  <%= f.button :submit %>
<% end %>